package com.bozgeyik.aisocialapp.ui.screens

import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import coil.compose.rememberAsyncImagePainter
import com.bozgeyik.aisocialapp.data.Post
import com.bozgeyik.aisocialapp.data.SupabaseClient
import io.github.jan.supabase.gotrue.auth
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.storage.storage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.UUID

@Composable
fun AddPostScreen(onPostAdded: () -> Unit) {
    var description by remember { mutableStateOf("") }
    var imageUri by remember { mutableStateOf<Uri?>(null) }
    var isAiGenerated by remember { mutableStateOf(false) }
    var isLoading by remember { mutableStateOf(false) }

    val scope = rememberCoroutineScope()
    val context = LocalContext.current

    // Galeri açıcı
    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        imageUri = uri
    }

    Column(
        modifier = Modifier.fillMaxSize().padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        // Resim Seçme Alanı
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(250.dp)
                .background(Color.LightGray)
                .clickable { launcher.launch("image/*") },
            contentAlignment = Alignment.Center
        ) {
            if (imageUri != null) {
                Image(
                    painter = rememberAsyncImagePainter(imageUri),
                    contentDescription = null,
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Crop
                )
            } else {
                Text("Resim Seçmek İçin Tıkla")
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        OutlinedTextField(
            value = description,
            onValueChange = { description = it },
            label = { Text("Açıklama Yaz") },
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(8.dp))

        Row(verticalAlignment = Alignment.CenterVertically) {
            Checkbox(checked = isAiGenerated, onCheckedChange = { isAiGenerated = it })
            Text("AI ile mi oluşturuldu?")
        }

        Spacer(modifier = Modifier.height(16.dp))

        if (isLoading) {
            CircularProgressIndicator()
        } else {
            Button(
                onClick = {
                    if (imageUri != null && description.isNotEmpty()) {
                        isLoading = true
                        scope.launch {
                            try {
                                // 1. Resmi Byte Array'e çevir
                                val byteArray = withContext(Dispatchers.IO) {
                                    context.contentResolver.openInputStream(imageUri!!)?.use {
                                        it.readBytes()
                                    }
                                }

                                if (byteArray != null) {
                                    // 2. Storage'a Yükle (Bucket adı: images)
                                    val fileName = "${UUID.randomUUID()}.jpg"
                                    val bucket = SupabaseClient.client.storage.from("images")
                                    bucket.upload(fileName, byteArray)

                                    // 3. Resmin Public Linkini Al
                                    val imageUrl = bucket.publicUrl(fileName)

                                    // 4. Veritabanına Yaz
                                    // Kullanıcı adını auth'dan alıyoruz, yoksa 'Anonim' yazıyoruz
                                    val currentUserEmail = SupabaseClient.client.auth.currentUserOrNull()?.email ?: "Anonim"
                                    val cleanUsername = currentUserEmail.split("@")[0]

                                    val newPost = Post(
                                        username = cleanUsername,
                                        description = description,
                                        image_url = imageUrl,
                                        is_ai_generated = isAiGenerated,
                                        like_count = 0
                                    )

                                    SupabaseClient.client.from("posts").insert(newPost)

                                    Toast.makeText(context, "Paylaşıldı!", Toast.LENGTH_SHORT).show()
                                    onPostAdded()
                                }
                            } catch (e: Exception) {
                                e.printStackTrace()
                                Toast.makeText(context, "Hata: ${e.message}", Toast.LENGTH_LONG).show()
                            } finally {
                                isLoading = false
                            }
                        }
                    } else {
                        Toast.makeText(context, "Lütfen resim ve açıklama girin", Toast.LENGTH_SHORT).show()
                    }
                },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("Paylaş")
            }
        }
    }
}